services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - myAppNet
  
  app:
    depends_on:
      - db
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - myAppNet

networks:
  myAppNet:

volumes:
  db_data: